# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
        exclude: tests/data/invalid.toml
      - id: check-yaml
        exclude: tests/data/invalid.yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies:
          - toml
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--config=.flake8", "rejected", "tests"]
        additional_dependencies:
          - flake8-comprehensions
          - flake8-deprecated
          - flake8-import-order
          - flake8-isort
          - flake8-print
          - flake8-pyproject
          - flake8-quotes
          - flake8-rst-docstrings
          - flake8-tuple
          - isort
